# Generated by Django 4.0.1 on 2022-01-23 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='formResponseGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_response', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_name', models.CharField(default=False, max_length=500, unique=True, verbose_name='field name')),
                ('form_description', models.CharField(default=False, max_length=10000, verbose_name='form description')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(default=False, max_length=500, verbose_name='field name')),
                ('field_type', models.CharField(default=True, max_length=250, verbose_name='type for field')),
                ('required', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='formTemplate.form')),
            ],
        ),
        migrations.CreateModel(
            name='FieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(default=False, max_length=500, verbose_name='response')),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('form_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_Response', to='formTemplate.form')),
                ('response_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='formTemplate.fields')),
                ('response_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='formTemplate.formresponsegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('choice_id', models.AutoField(primary_key=True, serialize=False)),
                ('choice_name', models.CharField(default=False, max_length=500, verbose_name='choice name')),
                ('for_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_choices', to='formTemplate.fields')),
            ],
        ),
    ]
