# Generated by Django 4.0.1 on 2022-01-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formTemplate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldresponse',
            name='form_response',
        ),
        migrations.AddField(
            model_name='formresponsegroup',
            name='form_response',
            field=models.ForeignKey(default='b23faced-7296-4d26-b36a-95eac9d08248', on_delete=django.db.models.deletion.CASCADE, related_name='form_Response', to='formTemplate.form'),
            preserve_default=False,
        ),
    ]
